default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rubydeveloper
  password: rubydeveloper

development:
  <<: *default
  database: santa_dev

test:
  <<: *default
  database: santa_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
